DROP DATABASE IF EXISTS reservas_app;
CREATE DATABASE reservas_app;
USE reservas_app;

-- TABLAS DIMENSIONALES
-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    TELEFONO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL,
    FECHA_ALTA DATETIME DEFAULT (CURRENT_TIMESTAMP),
    STATUS BOOLEAN DEFAULT TRUE
) COMMENT 'Tabla para almacenar información de los clientes';

-- Tabla DUEÑO
CREATE TABLE DUENO (
    IDDUENO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    CORREO VARCHAR(100),
    TELEFONO VARCHAR(20)
) COMMENT 'Tabla para almacenar información de los dueños de restaurantes';

-- Tabla TIPORESERVA
CREATE TABLE TIPORESERVA (
    IDTIPORESERVA INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(50)
) COMMENT 'Tabla para almacenar los diferentes tipos de reservas';

-- TABLAS CON FKS
-- Tabla EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(20),
    CORREO VARCHAR(100),
    IDRESTAURANTE INT
) COMMENT 'Tabla para almacenar información de los empleados';

-- Tabla RESTAURANTE
CREATE TABLE RESTAURANTE (
    IDRESTAURANTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20),
    IDDUENO INT
) COMMENT 'Tabla para almacenar información de los restaurantes';

-- Tabla MESA
CREATE TABLE MESA (
    IDMESA INT PRIMARY KEY AUTO_INCREMENT,
    IDRESTAURANTE INT,
    CAPACIDAD INT,
    DISPONIBLE BOOLEAN
) COMMENT 'Tabla para almacenar información de las mesas en los restaurantes';

-- TABLA HECHO
-- Tabla RESERVA
CREATE TABLE RESERVA (
    IDRESERVA INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT,
    IDMESA INT,
    IDEMPLEADO INT,
    IDTIPORESERVA INT,
    FECHA DATETIME,
    CANCELACION DATETIME DEFAULT NULL,
    HORARIO_RESERVA DATETIME
) COMMENT 'Tabla para almacenar información de las reservas';

-- FOREIGN KEYS DEFINITION
-- RESTAURANTE
ALTER TABLE RESTAURANTE ADD CONSTRAINT FK_REST_DUENO FOREIGN KEY (IDDUENO) REFERENCES DUENO (IDDUENO);

-- EMPLEADO
ALTER TABLE EMPLEADO ADD CONSTRAINT FK_EMP_CLIENTE FOREIGN KEY (IDRESTAURANTE) REFERENCES RESTAURANTE (IDRESTAURANTE);

-- MESA
ALTER TABLE MESA ADD CONSTRAINT FK_MESA_RESTAURANTE FOREIGN KEY (IDRESTAURANTE) REFERENCES RESTAURANTE (IDRESTAURANTE);

-- RESERVAS
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_MESA FOREIGN KEY (IDMESA) REFERENCES MESA (IDMESA);
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_EMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO (IDEMPLEADO);
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_TIPORESERVA FOREIGN KEY (IDTIPORESERVA) REFERENCES TIPORESERVA (IDTIPORESERVA);
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE);