-- GENERAR EL DDL

DROP DATABASE IF EXISTS proyecto_reservas ; -- reserv_ar

CREATE DATABASE proyecto_reservas;

USE proyecto_reservas;

-- Tabla RESERVA
CREATE TABLE RESERVA (
    IDRESERVA INT PRIMARY KEY AUTO_INCREMENT,
    IDCLIENTE INT,
    IDMESA INT,
    IDEMPLEADO INT,
    IDTIPORESERVA INT,
    FECHA DATETIME,
    CANCELACION DATETIME DEFAULT NULL
);

-- Tabla CLIENTE
CREATE TABLE CLIENTE (
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) DEFAULT 'USUARIO_UNKNOW',
    TELEFONO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL
);

-- Tabla EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMPLEADO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    TELEFONO VARCHAR(20),
    CORREO VARCHAR(100),
    IDRESTAURANTE INT
);

-- Tabla DUEÑO
CREATE TABLE DUENO (
    IDDUENO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    CORREO VARCHAR(100),
    TELEFONO VARCHAR(20)
);

-- Tabla TIPORESERVA
CREATE TABLE TIPORESERVA (
    IDTIPORESERVA INT PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(50)
);

-- Tabla RESTAURANTE
CREATE TABLE RESTAURANTE (
    IDRESTAURANTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20)
);

-- Tabla MESA
CREATE TABLE MESA (
    IDMESA INT PRIMARY KEY AUTO_INCREMENT,
    IDRESTAURANTE INT,
    CAPACIDAD INT,
    DISPONIBLE BOOLEAN
);



-- FOREIGN KEYS DEFINITION

-- EMPLEADO

ALTER TABLE EMPLEADO
    ADD CONSTRAINT FK_EMP_CLIENTE
    FOREIGN KEY (IDRESTAURANTE) REFERENCES RESTAURANTE(IDRESTAURANTE);
    
-- MESA
ALTER TABLE MESA
    ADD CONSTRAINT FK_MESA_RESTAURANTE
    FOREIGN KEY (IDRESTAURANTE) REFERENCES RESTAURANTE(IDRESTAURANTE);
    
-- RESERVAS

ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_CLIENTE
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_MESA
    FOREIGN KEY (IDMESA) REFERENCES MESA(IDMESA);

ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_EMPLEADO
    FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO);
    
ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_TIPORESERVA
    FOREIGN KEY (IDTIPORESERVA) REFERENCES TIPORESERVA(IDTIPORESERVA);